"""
study_notes.py
--------------
Feature 4: AI Study Notes Generator with PDF Export.
Summarizes a tutoring chat session into structured notes,
and exports them as a styled PDF using fpdf2.
"""

import os
import re
import json
import io
import google.generativeai as genai

API_KEY = os.getenv("GOOGLE_API_KEY")
if API_KEY:
    genai.configure(api_key=API_KEY)

MODEL_NAME = "gemini-2.5-flash-lite"


def generate_study_notes(chat_history: list, language: str = "c") -> dict:
    """
    Generate structured study notes from a chat session.

    Returns:
        {
            "title": str,
            "language": str,
            "key_concepts": [str],
            "code_snippets": [{"label": str, "code": str}],
            "common_mistakes": [str],
            "mini_quiz": [{"question": str, "answer": str}],
            "summary": str
        }
    """
    if not API_KEY:
        return {"error": "API key not configured"}

    if not chat_history:
        return {"error": "No chat history to summarize"}

    # Format history for prompt
    formatted_history = ""
    for msg in chat_history:
        role = "Student" if msg.get("role") == "user" else "Tutor"
        formatted_history += f"{role}: {msg.get('content', '')}\n\n"

    try:
        model = genai.GenerativeModel(MODEL_NAME)
        prompt = f"""You are an expert {language} programming tutor. A student just had a tutoring session.
Summarize the session into structured study notes they can review later.

Chat Session:
{formatted_history}

Respond ONLY with a valid JSON object (no markdown, no backticks):
{{
  "title": "A short descriptive title for these notes (e.g. 'Understanding Pointers in C')",
  "language": "{language.upper()}",
  "key_concepts": ["List of 3-6 key concepts covered in the session"],
  "code_snippets": [
    {{"label": "Concept name or short description", "code": "The relevant code snippet"}}
  ],
  "common_mistakes": ["2-4 common mistakes related to this session's topics"],
  "mini_quiz": [
    {{"question": "A short quiz question to test understanding", "answer": "The correct answer"}}
  ],
  "summary": "A 2-3 sentence paragraph summarizing what was learned in this session"
}}

Include 1-3 code snippets and 2-3 quiz questions. Make notes beginner-friendly.
"""
        response = model.generate_content(
            prompt,
            generation_config={"temperature": 0.3, "max_output_tokens": 2000}
        )
        raw = response.text.strip()
        raw = re.sub(r"```(?:json)?", "", raw).strip().strip("```").strip()

        try:
            notes = json.loads(raw)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", raw, re.DOTALL)
            if match:
                notes = json.loads(match.group())
            else:
                raise ValueError("Could not parse JSON from response")

        return notes

    except Exception as e:
        return {"error": str(e)}


def export_pdf(notes: dict) -> bytes:
    """
    Export study notes as a styled PDF using fpdf2.
    Returns PDF bytes.
    """
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # ---- Title ----
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 12, txt=notes.get("title", "Study Notes"), ln=True, align="C")

        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 7, txt=f"Language: {notes.get('language', '')}  |  Generated by CodeTutor AI", ln=True, align="C")
        pdf.ln(5)

        # Divider
        pdf.set_draw_color(200, 120, 92)
        pdf.set_line_width(0.7)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(8)

        def section_title(title: str, r=204, g=120, b=92):
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(r, g, b)
            pdf.cell(0, 9, txt=title, ln=True)
            pdf.set_text_color(30, 30, 30)
            pdf.ln(1)

        def body_text(text: str):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            # Replace non-latin characters that might cause encoding issues
            safe_text = text.encode("latin-1", errors="replace").decode("latin-1")
            pdf.multi_cell(0, 6, txt=safe_text)
            pdf.ln(1)

        # ---- Summary ----
        section_title("📖 Session Summary")
        body_text(notes.get("summary", ""))
        pdf.ln(3)

        # ---- Key Concepts ----
        section_title("🔑 Key Concepts")
        for concept in notes.get("key_concepts", []):
            pdf.set_font("Helvetica", "", 10)
            safe = concept.encode("latin-1", errors="replace").decode("latin-1")
            pdf.cell(6, 6, txt="", ln=False)
            pdf.cell(0, 6, txt=f"• {safe}", ln=True)
        pdf.ln(3)

        # ---- Code Snippets ----
        snippets = notes.get("code_snippets", [])
        if snippets:
            section_title("💻 Code Snippets")
            for snip in snippets:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(80, 80, 80)
                label = snip.get("label", "").encode("latin-1", errors="replace").decode("latin-1")
                pdf.cell(0, 7, txt=label, ln=True)
                pdf.set_font("Courier", "", 9)
                pdf.set_fill_color(30, 30, 30)
                pdf.set_text_color(230, 230, 230)
                code = snip.get("code", "").encode("latin-1", errors="replace").decode("latin-1")
                for line in code.split("\n"):
                    pdf.cell(0, 5, txt=f"  {line}", ln=True, fill=True)
                pdf.set_text_color(30, 30, 30)
                pdf.set_fill_color(255, 255, 255)
                pdf.ln(3)

        # ---- Common Mistakes ----
        mistakes = notes.get("common_mistakes", [])
        if mistakes:
            section_title("⚠️ Common Mistakes to Avoid")
            for mistake in mistakes:
                safe = mistake.encode("latin-1", errors="replace").decode("latin-1")
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(200, 80, 80)
                pdf.cell(0, 6, txt=f"  ✗  {safe}", ln=True)
            pdf.set_text_color(30, 30, 30)
            pdf.ln(3)

        # ---- Mini Quiz ----
        quiz = notes.get("mini_quiz", [])
        if quiz:
            section_title("🧠 Mini Quiz")
            for i, item in enumerate(quiz, 1):
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(50, 50, 50)
                q = item.get("question", "").encode("latin-1", errors="replace").decode("latin-1")
                pdf.multi_cell(0, 6, txt=f"Q{i}. {q}")
                pdf.set_font("Helvetica", "I", 10)
                pdf.set_text_color(80, 120, 80)
                a = item.get("answer", "").encode("latin-1", errors="replace").decode("latin-1")
                pdf.multi_cell(0, 6, txt=f"    → {a}")
                pdf.ln(2)

        # ---- Footer ----
        pdf.set_y(-20)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 5, txt="Generated by CodeTutor AI  •  Keep learning!", ln=True, align="C")

        return bytes(pdf.output())

    except ImportError:
        raise RuntimeError("fpdf2 is not installed. Run: pip install fpdf2")
    except Exception as e:
        raise RuntimeError(f"PDF generation failed: {e}")
